### ISSUE TITLE
Transposes?

### ISSUE THREAD

**Issue by elbriggs** [eth-cscs/Tiled-MM#10] opened 2023-01-03 18:31 UTC
I've been looking for a suitable cublasxt equivalent for AMD GPUs but require the ability to do multiply the transpose of a matrix by another and the API does not seem to support that. Or am I missing something?

**Comment by kabicm** [comment] 2023-01-03 18:38
This should be easy to add - e.g. for dgemm, you should modify this line:
https://github.com/eth-cscs/Tiled-MM/blob/9e880f94d1c46114d514de3c33ef58c62b5a95ca/src/Tiled-MM/tiled_mm.cpp#L162

and instead of `blas_api::operation::None` pass `blas_api::operation::Transpose`. Similarly for sgemm and others.

Ideally, our wrapper should be extended and pass this variable down to the cublas wrapper.

**Comment by elbriggs** [comment] 2023-01-04 00:21
I started experimenting with this and the non-transposed case works well but when I made the change suggested above I got an error

error: BLAS API call: rocblas_status_invalid_size

that would seem to indicate some mixup with m,n and k. I am passing them to the upper level routine in the same way I would for a standard dgemm call with the A matrix transposed.

**Comment by simonpintarelli** [comment] 2023-01-04 09:24
It looks correct to me, the call to `blas_api::dgemm` in https://github.com/eth-cscs/Tiled-MM/blob/9e880f94d1c46114d514de3c33ef58c62b5a95ca/src/Tiled-MM/tiled_mm.cpp#L162
is directly forwarded to `rocblas_dgemm` (cf https://github.com/eth-cscs/Tiled-MM/blob/master/src/Tiled-MM/gpu_blas_api.hpp#L216)

Did you correctly specify `m,n,k` for the transposed case, e.g. `m=ncols(A)` in case A is transposed?

**Comment by elbriggs** [comment] 2023-01-04 13:57
Yes. The call to gpu::gemm is using the exact same args as the hipblas call it is replacing (minus the leading dims since the Tiled-MM API does not support that but the matrices are not padded in any case). I am using ROCM 5.4.0 and there are some warnings about a deprecated include but this seems unlikely to be an issue.

/opt/rocm/include/rocblas.h:16:160: note: ‘#pragma message: : warning : This file is deprecated. Use the header file from /opt/rocm-5.4.0/include/rocblas/rocblas.h by using #include <rocblas/rocblas.h>’

**Comment by kabicm** [comment] 2023-01-04 14:03
Thanks @simonpintarelli, that's a good catch!

@elbriggs I will try to add the transpose/conjugate flags today and will test it on nvidia gpus. Will keep you updated!

**Comment by kabicm** [comment] 2023-01-05 01:06
@simonpintarelli @elbriggs I made a [PR](https://github.com/eth-cscs/Tiled-MM/pull/11) that will add this feature. However, it's still work in progress as I realized that also the tile sizes have to consistently change based on the transpose flags.

**Comment by kabicm** [comment] 2023-01-20 02:22
@elbriggs we will tomorrow release a new version which will have transpose flags as well as leading dimensions arguments, thus supporting the full cublasXt API.

**Comment by elbriggs** [comment] 2023-01-20 12:02
Excellent! Looking forward to trying it!

**Comment by kabicm** [comment] 2023-01-20 16:55
@elbriggs The latest master version now supports both the transpose/conjugate flags, as well as the leading dimensions. The API is almost the same as the standard cublas/rocblas.

Checkout the README which is and especially the [benchmarking section](https://github.com/eth-cscs/Tiled-MM#running-the-benchmarks), as it offers a lot of command-line options that you can play with.

**Comment by elbriggs** [comment] 2023-01-20 19:06
@kabicm I haven't done  detailed benchmarking yet but initial tests on my workstation (Radeon VII GPUs) look good. For our purposes the real plus is being able to do calculations on AMD based systems where the matrices won't fit into GPU memory. Next step is tests on MI250X GPUs. (Using Crusher/Frontier).

**Comment by kabicm** [comment] 2023-01-20 19:20
sure! would be curious to hear about the performance you are getting - just make sure to try out different tile sizes, they can have impact on the performance. 

And in case you need a distributed version of Tiled-MM over multiple nodes/gpus, you can try out [COSMA](https://github.com/eth-cscs/COSMA). COSMA is using Tiled-MM as a gpu backend.

**Comment by kabicm** [comment] 2023-01-22 15:15
Closing this issue now.

**Closed by kabicm** 2023-01-22 15:15 UTC

**Comment by elbriggs** [comment] 2023-01-22 15:24
Everything looks good using float and double matrices. I've had some problems in our application with complex data which I am still trying to track down.

**Comment by kabicm** [comment] 2023-01-22 15:29
If you think the problem is in Tiled-MM, you can share the test case with us. You might use the testing miniapp that we provide in the tests folder (see README) to test the correctness for specific matrix sizes and other arguments.

**Comment by elbriggs** [comment] 2023-01-22 15:35
OK. I'm still not sure if the issue is in Tiled-MM but should know soon. I used the test app for the double case but it doesn't appear to have an option to test complex data types.
